#!/bin/bash

ROOT_DIR=$(dirname "$0")/../..

if [[ -z `which php` ]]; then
  exit
fi

if [[ -z `which phpcbf` ]]; then
  # use vendor phpcbf
  PHP_CBF_PATH=$ROOT_DIR/src/vendor/bin/phpcbf
else
  # use global phpcbf
  PHP_CBF_PATH=$(which phpcbf)
fi

$PHP_CBF_PATH --version

for FILE in $(git diff-index --cached --name-only HEAD); do
  if [[ $FILE =~ \.php$ && -f $FILE ]]; then
    echo "format: $FILE"
    $PHP_CBF_PATH -w --standard=$ROOT_DIR/src/phpcs.xml $ROOT_DIR/$FILE
    git add $ROOT_DIR/$FILE
  fi
done